import type { Metadata } from "next";
import { Inter, Manrope, Outfit } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import LoadingStateContextProvider from "@/context/loadingStateContext";
import Navbar from "@/components/navbar";
import { Analytics } from "@vercel/analytics/react";

const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" relative">
      <body
        className={cn(
          inter.className,
          "dark bg-backgroundColor text-textColor"
        )}
      >
        <LoadingStateContextProvider>
          <Navbar />
          {children}
          <Analytics />
        </LoadingStateContextProvider>
      </body>
    </html>
  );
}
