import type { Metadata } from "next";
import { Inter, Manrope, Outfit } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import LoadingStateContextProvider from "@/context/loadingStateContext";

const inter = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" relative">
      <body className={cn(inter.className, "calm-thoughts")}>
        <LoadingStateContextProvider>{children}</LoadingStateContextProvider>
      </body>
    </html>
  );
}
